In [1]:
import numpy as np

# Array

In [3]:
a = np. array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [4]:
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
print (a[0])

[1 2 3 4]


# Creating Array

In [6]:
b = np.array([1,2,3])

In [7]:
b

array([1, 2, 3])

In [8]:
c = np.zeros(6)

In [9]:
c

array([0., 0., 0., 0., 0., 0.])

In [10]:
d = np.ones(6)

In [11]:
d

array([1., 1., 1., 1., 1., 1.])

In [13]:
e = np.empty(6)

In [14]:
e

array([1., 1., 1., 1., 1., 1.])

In [15]:
f = np.arange(4)

In [16]:
f

array([0, 1, 2, 3])

In [17]:
g = np.arange(0, 30, 3)

In [18]:
g

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

# Add, Remove, and Sort

In [19]:
h = np.arange(0,100,1)

In [22]:
h

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
np.append(h, np.arange(100, 121, 1))

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120])

In [31]:
i = np.append(h, np.arange(100, 121, 1))

In [32]:
print(i)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120]


In [33]:
j = np.delete(g, np.arange(20, 50, 3))

In [35]:
print (j)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  21  22  24  25  27  28  30  31  33  34  36  37  39  40  42  43
  45  46  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120]


In [36]:
k = np.append(j, np.arange(70, 81, 2))

In [37]:
print(k)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  21  22  24  25  27  28  30  31  33  34  36  37  39  40  42  43
  45  46  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120  70  72  74  76  78  80]


In [38]:
k = np.sort(k)

In [39]:
k

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  21,  22,  24,  25,  27,  28,
        30,  31,  33,  34,  36,  37,  39,  40,  42,  43,  45,  46,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  70,  71,  72,  72,
        73,  74,  74,  75,  76,  76,  77,  78,  78,  79,  80,  80,  81,
        82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107,
       108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])

In [75]:
k.size

117

In [91]:
k1 = np.delete(k, [np.arange(0,17,1)])


In [92]:
print(k1)

[ 17  18  19  21  22  24  25  27  28  30  31  33  34  36  37  39  40  42
  43  45  46  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62
  63  64  65  66  67  68  69  70  70  71  72  72  73  74  74  75  76  76
  77  78  78  79  80  80  81  82  83  84  85  86  87  88  89  90  91  92
  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110
 111 112 113 114 115 116 117 118 119 120]


In [93]:
k1.size

100

In [97]:
k2 = k1.reshape(4,5,5)

In [98]:
print(k2)

[[[ 17  18  19  21  22]
  [ 24  25  27  28  30]
  [ 31  33  34  36  37]
  [ 39  40  42  43  45]
  [ 46  48  49  50  51]]

 [[ 52  53  54  55  56]
  [ 57  58  59  60  61]
  [ 62  63  64  65  66]
  [ 67  68  69  70  70]
  [ 71  72  72  73  74]]

 [[ 74  75  76  76  77]
  [ 78  78  79  80  80]
  [ 81  82  83  84  85]
  [ 86  87  88  89  90]
  [ 91  92  93  94  95]]

 [[ 96  97  98  99 100]
  [101 102 103 104 105]
  [106 107 108 109 110]
  [111 112 113 114 115]
  [116 117 118 119 120]]]


In [99]:
k3 = k2.reshape(2,5,2,5)
print (k3)

[[[[ 17  18  19  21  22]
   [ 24  25  27  28  30]]

  [[ 31  33  34  36  37]
   [ 39  40  42  43  45]]

  [[ 46  48  49  50  51]
   [ 52  53  54  55  56]]

  [[ 57  58  59  60  61]
   [ 62  63  64  65  66]]

  [[ 67  68  69  70  70]
   [ 71  72  72  73  74]]]


 [[[ 74  75  76  76  77]
   [ 78  78  79  80  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]]

  [[ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]]

  [[111 112 113 114 115]
   [116 117 118 119 120]]]]


In [100]:
k4=k2.reshape(5,2,5,2)
print(k4)

[[[[ 17  18]
   [ 19  21]
   [ 22  24]
   [ 25  27]
   [ 28  30]]

  [[ 31  33]
   [ 34  36]
   [ 37  39]
   [ 40  42]
   [ 43  45]]]


 [[[ 46  48]
   [ 49  50]
   [ 51  52]
   [ 53  54]
   [ 55  56]]

  [[ 57  58]
   [ 59  60]
   [ 61  62]
   [ 63  64]
   [ 65  66]]]


 [[[ 67  68]
   [ 69  70]
   [ 70  71]
   [ 72  72]
   [ 73  74]]

  [[ 74  75]
   [ 76  76]
   [ 77  78]
   [ 78  79]
   [ 80  80]]]


 [[[ 81  82]
   [ 83  84]
   [ 85  86]
   [ 87  88]
   [ 89  90]]

  [[ 91  92]
   [ 93  94]
   [ 95  96]
   [ 97  98]
   [ 99 100]]]


 [[[101 102]
   [103 104]
   [105 106]
   [107 108]
   [109 110]]

  [[111 112]
   [113 114]
   [115 116]
   [117 118]
   [119 120]]]]


# Shape and Size

In [42]:
l= np.array([[[0, 1, 2, 3],
                    [4, 5, 6, 7]],
                  
                  [[0, 1, 2, 3],
                    [4, 5, 6, 7]],
                    
                  [[0, 1, 2, 3],
                    [4, 5, 6, 7]]])

In [43]:
print (l)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [44]:
l.ndim

3

In [45]:
l.size

24

In [46]:
l.shape

(3, 2, 4)

In [66]:
m = np.array([np.arange(1, 6)])

In [67]:
m.ndim

2

In [68]:
m.size

5

In [69]:
m.shape

(1, 5)

In [70]:
print(m)

[[1 2 3 4 5]]


# Reshape

In [63]:
n = np.arange(6)
print (n)

[0 1 2 3 4 5]


In [72]:
n.size

6

In [73]:
o = n.reshape(3,2)

In [74]:
print(o)

[[0 1]
 [2 3]
 [4 5]]


In [102]:
o.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# 1D to 2D

In [104]:
q = np.arange(1, 10, 1)

In [105]:
q.shape

(9,)

In [106]:
q1 = q[np.newaxis]

In [107]:
print(q1.shape)

(1, 9)


In [108]:
print (q1)

[[1 2 3 4 5 6 7 8 9]]


In [110]:
q2_rowvector = q[np.newaxis, :]
print(q2_rowvector)
print(q2_rowvector.shape)

[[1 2 3 4 5 6 7 8 9]]
(1, 9)


In [112]:
q2_colvector = q[:, np.newaxis]
print(q2_colvector)
print(q2_colvector.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(9, 1)


In [113]:
r = np.arange(1, 10, 1)
r.shape

(9,)

In [114]:
r1 = np.expand_dims(r, axis=1)
r1.shape

(9, 1)

In [115]:
r1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [120]:
r2 = np.expand_dims(r, axis=0)
print (r2)
r2.shape

[[1 2 3 4 5 6 7 8 9]]


(1, 9)

# Index and Slicing

In [123]:
s = np.arange(0, 100, 1)
s

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [124]:
print(s)
print(s[0])
print(s[50])
print(s[75:90])
print(s[-50:-25])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
0
50
[75 76 77 78 79 80 81 82 83 84 85 86 87 88 89]
[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74]


In [125]:
t = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
t

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [126]:
t1 = t[t>=5]
t1

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [128]:
t2 = t[t%2==0]
t2

array([ 2,  4,  6,  8, 10, 12])

In [129]:
t3 = t[(t>3) & (t<10)]
t3

array([4, 5, 6, 7, 8, 9])

# Creating array dari data yang ada