In [1]:
import numpy as np

# 3 Dimensi

In [11]:
ex = np.array([[[1, 2, 3, 4], 
                        [5, 6, 7, 8]], 
                        [[9, 10, 11, 12], 
                        [13, 14, 15, 16]], 
                        [[17, 18, 19, 20],
                        [21, 22, 23, 24]]])

print(ex)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [12]:
print(ex.ndim)
print(ex.size)
print(ex.shape)

3
24
(3, 2, 4)


# 4 Dimensi

In [17]:
a = np.array([[[1, 2, 3, 4], 
                    [5, 6, 7, 8]], 
                    [[9, 10, 11, 12], 
                    [13, 14, 15, 16]], 
                    [[17, 18, 19, 20],
                    [21, 22, 23, 24]],
                    [[25, 26, 27, 28],
                    [29, 30, 31, 32]]])

In [18]:
print(a)
print(a.ndim)
print(a.size)
print(a.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]]]
3
32
(4, 2, 4)
