In [1]:
import numpy as np

In [4]:
a1 = np.array([[1,1], [2,2]])
a2 = np.array([[3,3], [4,4]])
print(a1)
print(a2)


[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [5]:
print(np.vstack((a1,a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [6]:
print(np.hstack((a1,a2)))

[[1 1 3 3]
 [2 2 4 4]]


In [11]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,21,22,23,24])

In [13]:
b1=np.hsplit(b, 4)
b2=b.view()
b3=b.copy()


In [14]:
print(b1)


[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12]), array([13, 14, 15, 16, 17, 18]), array([19, 20, 21, 22, 23, 24])]


In [15]:
print(b2)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [16]:
print(b3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
