In [1]:
import numpy as np

In [2]:
e = np.array([[ 11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22], [23, 24, 25, 26], [27, 28, 29, 30]])

In [3]:
print(e)

[[11 12 13 14]
 [15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]


In [5]:
print(e[e>=13])

[13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [6]:
e2=(e>=10)
print(e[e2])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
